### ISSUE TITLE
Running Integration Tests with pocket-ic

### ISSUE THREAD

**Issue by wirapratamaz** [domwoe/schnorr_canister#1]
Hi Domwoe,

I've recently come across your repository related to integration testing with pocket-ic. I've already filled in the dependency pocket-ic = "2.0.1" in my cargo.toml. However, I'm facing difficulties in understanding how to run the tests. I noticed in your readme.md you mentioned:

"Please make sure to have it installed and the POCKET_IC_BIN environment variable set to the path of the pocket-ic binary."

Could you provide guidance on how to proceed with this? I would greatly appreciate your assistance.

**Comment by domwoe** [comment]
Hi @wirapratamaz,

I should add the link to https://github.com/dfinity/pocketic.

You need to download the Pocket IC server binary and set the `POCKET_IC_BIN` environment variable to point to this binary.

**Comment by wirapratamaz** [comment]
I already download and unzip the file and set the POCKET_IC_BIN environment variable, but still cannot running ./pocket-ic. How about this sir??
![pocket ic](https://github.com/domwoe/schnorr_canister/assets/89260515/813e3a6d-f769-4b13-813a-db5939061e47)

**Comment by domwoe** [comment]
This looks like you are trying to run a binary that doesn't fit your architecture. Did you download the proper release for your architecture? 

What system are you on and which release of PocketIC did you download?

**Comment by wirapratamaz** [comment]
Yeah I already download with the same achitecture https://github.com/dfinity/pocketic/tree/2.0.1
my system is Windows, but I use wsl-2 to bring Ubuntu-20 command line
